### ISSUE TITLE
chapter5/chapter7: install_fleetctl_and_scripts.sh doesn't work, prompting for password

### ISSUE THREAD

**Issue by tobkle** [rimusz/coreos-essentials-book#1]
FLEET_RELEASE=$(ssh core@$control_ip fleetctl version | cut -d " " -f 3- | tr -d '\r')

leads to a password prompt on the core@$control_ip, but there is no generated password.

**Comment by tobkle** [comment]
Did now this, to get over that:
Went to Google Cloud Engine Console opened ssh there and entered the command directly to get the version number of etcd.
Then changed the script to the found version number:
    # FLEET_RELEASE=$(ssh core@$control_ip fleetctl version | cut -d " " -f 3- | tr -d '\r')
    FLEET_RELEASE=0.10.2

**Comment by rimusz** [comment]
@tobkle it sometimes happens after first boot of coreos VM on GCE to be asked for the password.
Reboot of the VM usually solves the problem.

**Comment by tobkle** [comment]
thanks rimusz, unfortunately that didn't work.

Solved it now by changing the script line from ssh to "gcloud compute ssh" like this:
FLEET_RELEASE=$(**gcloud compute --project=$project ssh  --zone=$zone "core@prod-control1" --command "fleetctl version | cut -d ' ' -f 3- | tr -d '\r' ")**

**Comment by rimusz** [comment]
@tobkle I will go over the scripts again (it was done so many times), might use your fix there, thanks

**Comment by rimusz** [comment]
scripts are updated/fixed
