### ISSUE TITLE
chapter6: webserver/deploy_2_staging1.sh doesn't work

### ISSUE THREAD

**Issue by tobkle** [rimusz/coreos-essentials-book#2]
password required: added to copy-files core@dest_path
thereafter...
permission denied: root is owner of the share path, so chowned to core user instead:

gcloud compute --project=$project ssh  --zone=$zone "core@tsc-staging1" --command "sudo chmod -R 755 /home/core/share/"
**gcloud compute --project=$project ssh  --zone=$zone "core@tsc-staging1" --command "sudo chown -R core /home/core/share/"**

echo "Deploying code to tsc-staging1 server !!!"
gcloud compute copy-files staging1/index.html **core@**tsc-staging1:/home/core/share/nginx/html --zone $zone --project $project

**Comment by rimusz** [comment]
@tobkle thanks, updated
