### ISSUE TITLE
Chapter7: Script error

### ISSUE THREAD

**Issue by tobkle** [rimusz/coreos-essentials-book#3]
Script: coreos-essentials-book/chapter7/Test_Staging_Cluster/install_website1_2_dbuilder.sh
throws errors:
ERROR: (gcloud.compute.copy-files) All sources must be remote files when the destination is local.

Changed the script to these lines:

echo "Deploy docker image building script to tsc-registry-cbuilder1 server !!!"
gcloud compute ssh --project=$project  --zone=$zone "core@tsc-registry-cbuilder1"  --command "sudo chmod o+w /home/core/data"
gcloud compute copy-files files/\* core@tsc-registry-cbuilder1:/home/core/data --zone $zone --project $project
gcloud compute ssh --project=$project  --zone=$zone "core@tsc-registry-cbuilder1"  --command "sudo chmod 755 /home/core/data/*.sh"

**Comment by rimusz** [comment]
@tobkle thanks, updated
